# Generated by Django 5.2.11 on 2026-02-19 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('nurse_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_wards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward')),
            ],
            options={
                'unique_together': {('ward', 'bed_no')},
            },
        ),
    ]
