# Generated by Django 5.2.11 on 2026-02-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='admited_at',
            new_name='admitted_at',
        ),
    ]
